# Generated by Django 5.1.6 on 2025-02-24 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_api_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_api_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('telegram_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('telegram_session_file', models.CharField(blank=True, max_length=128, null=True)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('email_enabled', models.BooleanField(default=False)),
                ('email_imap_host', models.CharField(blank=True, max_length=255, null=True)),
                ('email_imap_port', models.PositiveIntegerField(blank=True, default=993, null=True)),
                ('email_imap_user', models.CharField(blank=True, max_length=255, null=True)),
                ('email_imap_password', models.CharField(blank=True, max_length=255, null=True)),
                ('email_imap_ssl', models.BooleanField(default=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.PositiveIntegerField(blank=True, default=587, null=True)),
                ('smtp_user', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('phonet_ext', models.CharField(blank=True, help_text='Внутрішній номер (ext) співробітника в Phonet', max_length=32, null=True)),
                ('phonet_enabled', models.BooleanField(default=False, help_text='Активувати прослуховування викликів для цього користувача?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
