# Generated by Django 5.1.6 on 2025-02-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_telegram_session_file_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='robota_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Robota.ua ID'),
        ),
        migrations.AddField(
            model_name='company',
            name='work_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Work.ua ID'),
        ),
    ]
