# Generated by Django 5.1.7 on 2025-04-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_companies_needing_attention',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
