# Generated by Django 5.1.6 on 2025-02-25 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonet_uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Унікальний UUID від Phonet')),
                ('parent_uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='UUID батьківського виклику, якщо є')),
                ('direction', models.PositiveSmallIntegerField(help_text='1=internal, 2=outgoing, 4=incoming, etc.', verbose_name='Напрямок дзвінка')),
                ('leg_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Leg ID (Phonet)')),
                ('leg_ext', models.CharField(blank=True, max_length=50, null=True, verbose_name='Внутр. номер (ext) користувача')),
                ('leg_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Ім'я/назва користувача (Phonet)")),
                ('client_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон клієнта')),
                ('dial_at', models.DateTimeField(blank=True, null=True, verbose_name='Час початку дзвінка (call.dial)')),
                ('bridge_at', models.DateTimeField(blank=True, null=True, verbose_name='Час підняття слухавки (call.bridge)')),
                ('hangup_at', models.DateTimeField(blank=True, null=True, verbose_name='Час завершення дзвінка (call.hangup)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('interaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_message', to='sales.interaction', verbose_name='Взаємодія (дзвінок)')),
            ],
        ),
    ]
