# Generated by Django 5.1.6 on 2025-02-26 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_companyjust_company_created_at_company_responsible_and_more'),
        ('sales', '0002_callmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тайтл')),
                ('created_at', models.DateTimeField(verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оновлення')),
                ('placement', models.CharField(choices=[('work', 'Work'), ('robota', 'Robota'), ('just', 'Just')], max_length=20, verbose_name='Розміщення')),
                ('work_id', models.IntegerField(blank=True, null=True, verbose_name='Work.ua ID')),
                ('robota_id', models.IntegerField(blank=True, null=True, verbose_name='Robota.ua ID')),
                ('just_id', models.IntegerField(blank=True, null=True, verbose_name='Just ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='main.company', verbose_name='Компанія')),
            ],
        ),
    ]
