# Generated by Django 5.1.6 on 2025-02-26 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_companyjust_company_created_at_company_responsible_and_more'),
        ('sales', '0004_alter_vacancy_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='Гаряча вакансія'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='robota_company_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Robota компані ID'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_company_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Work компані ID'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='main.company', verbose_name='Компанія'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення'),
        ),
    ]
