# Generated by Django 5.1.6 on 2025-03-20 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_contactlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('task_date', models.DateTimeField(verbose_name='Дата задачі')),
                ('task_type', models.CharField(choices=[('call', 'Дзвінок'), ('email', 'Лист'), ('message', 'Повідомлення')], max_length=20, verbose_name='Тип задачі')),
                ('target', models.CharField(max_length=255, verbose_name='Ціль')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата виконання')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sales.contact', verbose_name='Контакт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачі',
            },
        ),
    ]
