# Generated by Django 5.1.6 on 2025-03-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_company_slug'),
        ('sales', '0007_task'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['work_company_id'], name='sales_vacan_work_co_39c1b5_idx'),
        ),
    ]
